++ healthchecks to pg&redis
safe-global/safe-infrastructure pull request #105
Opened 2023-07-28 15:02 UTC by mshakeg

Fixes #104

2023-07-28 15:05 UTC, mshakeg commented
[Contributor License Agreement](https://safe.global/cla/) returns Page Not Found

2023-08-01 13:20 UTC, Uxio0 commented
> [Contributor License Agreement](https://safe.global/cla/) returns Page Not Found

Noted, there was a typo on the url! Thanks! https://github.com/safe-global/safe-infrastructure/pull/108

2023-08-01 13:22 UTC, Uxio0 requested changes
Thank you very much for PR!

2023-08-01 13:22 UTC, Uxio0 commented on docker-compose.yml
> +    healthcheck:
Could you inherit using `<<:` yaml so you don't have to define the same liveness multiple times for redis and postgres?

2023-08-01 19:27 UTC, mshakeg commented
I have read the CLA Document and I hereby sign the CLA

recheck

2023-08-01 19:29 UTC, mshakeg commented
recheck

2023-08-02 11:28 UTC, Uxio0 approved these changes
Really nice, thanks!

2023-08-02 12:13 UTC, merged