Add flower
safe-global/safe-infrastructure pull request #45
Opened 2022-08-03 11:15 UTC by moisses89

Closes #44

2022-08-03 12:03 UTC, Uxio0 requested changes

2022-08-03 12:03 UTC, Uxio0 commented on docker-compose.yml
> +  txs-flower:
I would add this in a separate docker-compose file: https://docs.docker.com/compose/extends/

2022-08-03 16:02 UTC, Uxio0 approved these changes
I think by convention (https://docs.docker.com/compose/extends/) it should be `docker-compose.monitoring.yml`

2022-08-04 07:21 UTC, moisses89 commented
> I think by convention (https://docs.docker.com/compose/extends/) it should be `docker-compose.monitoring.yml`

Good point! :)

2022-08-04 07:23 UTC, merged